version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - food-array
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: S0l34d0123

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - food-array
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: S0l34d0123
      ME_CONFIG_MONGODB_URL: mongodb://root:S0l34d0123@mongo:27017/

networks:
  food-array: